#include "kernel.hpp"

#include <iostream>
#include <chrono>
#include <cuda_fp16.h>
#include <cudnn.h>
#include <mma.h>
#include <cuda_runtime.h>

#include "shape.hpp"
#include "common/fmt.hpp"
#include "common/utils.hpp"

// Computes ceil(x / y)
template <class T>
__host__ __device__ T ceil_div(T x, T y) {
  T offset = x % y == 0 ? 0 : 1;
  return x / y + offset;
}

// This function is generated by genmini.
void checkCudnn(cudnnStatus_t status) {
    if (status != CUDNN_STATUS_SUCCESS) {
        std::cerr << "cuDNN Error: " << cudnnGetErrorString(status) << std::endl;
        exit(EXIT_FAILURE);
    }
}

// This function is generated by genmini.
void run_cudnn_convolution(
    const __half* d_input,  int in_n, int in_c, int in_h, int in_w,
    const __half* d_filter, int filt_k, int filt_c, int filt_h, int filt_w,
    __half* d_output, int pad_h, int pad_w, int str_h, int str_w)
{
    cudnnHandle_t cudnn;
    checkCudnn(cudnnCreate(&cudnn));

    // --- 1. Describe Input Tensor (NCHW layout with CUDNN_DATA_HALF) ---
    cudnnTensorDescriptor_t input_desc;
    checkCudnn(cudnnCreateTensorDescriptor(&input_desc));
    checkCudnn(cudnnSetTensor4dDescriptor(input_desc, CUDNN_TENSOR_NCHW, CUDNN_DATA_HALF,
                                          in_n, in_c, in_h, in_w));

    // --- 2. Describe Filter (KCHW layout with CUDNN_DATA_HALF) ---
    cudnnFilterDescriptor_t filter_desc;
    checkCudnn(cudnnCreateFilterDescriptor(&filter_desc));
    checkCudnn(cudnnSetFilter4dDescriptor(filter_desc, CUDNN_DATA_HALF, CUDNN_TENSOR_NCHW,
                                          filt_k, filt_c, filt_h, filt_w));

    // --- 3. Describe Convolution Math ---
    // Note: We use CUDNN_DATA_FLOAT for math precision (Pseudo-FP16 mode).
    // This accumulates math in FP32 to prevent underflow/overflow, which is highly
    // recommended by NVIDIA for performance and stability on Tensor Cores.
    cudnnConvolutionDescriptor_t conv_desc;
    checkCudnn(cudnnCreateConvolutionDescriptor(&conv_desc));
    checkCudnn(cudnnSetConvolution2dDescriptor(conv_desc, pad_h, pad_w, str_h, str_w,
                                               1, 1, CUDNN_CROSS_CORRELATION, CUDNN_DATA_FLOAT));

    // Explicitly enable Tensor Core acceleration math mode if needed (cuDNN 8 usually handles this automatically)
    checkCudnn(cudnnSetConvolutionMathType(conv_desc, CUDNN_DEFAULT_MATH));

    // --- 4. Determine Output Shape ---
    int out_n, out_c, out_h, out_w;
    checkCudnn(cudnnGetConvolution2dForwardOutputDim(conv_desc, input_desc, filter_desc,
                                                     &out_n, &out_c, &out_h, &out_w));

    cudnnTensorDescriptor_t output_desc;
    checkCudnn(cudnnCreateTensorDescriptor(&output_desc));
    checkCudnn(cudnnSetTensor4dDescriptor(output_desc, CUDNN_TENSOR_NCHW, CUDNN_DATA_HALF,
                                          out_n, out_c, out_h, out_w));

#if 0
    // --- 5. Find Best Algorithm (Modern cuDNN 8+ Approach) ---
    int requested_algo_count = 1;
    int returned_algo_count = 0;
    cudnnConvolutionFwdAlgoPerf_t perf_results;

    checkCudnn(cudnnFindConvolutionForwardAlgorithm(
        cudnn,
        input_desc,
        filter_desc,
        conv_desc,
        output_desc,
        requested_algo_count,
        &returned_algo_count,
        &perf_results));

    cudnnConvolutionFwdAlgo_t algo = perf_results.algo;
    size_t workspace_size = perf_results.memory;

    if (perf_results.status != CUDNN_STATUS_SUCCESS) {
      std::cerr << "No suitable algorithm found!" << std::endl;
      exit(EXIT_FAILURE);
    }
#else
    cudnnConvolutionFwdAlgo_t algo = CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM;
    std::size_t workspace_size;
    checkCudnn(cudnnGetConvolutionForwardWorkspaceSize(
      cudnn,
      input_desc,
      filter_desc,
      conv_desc,
      output_desc,
      algo,
      &workspace_size
    ));
#endif
    std::cout << "CuDNN using algorithm: " << static_cast<int>(algo) << std::endl;
    std::cout << "Workspace size: " << workspace_size << std::endl;

    void* d_workspace{nullptr};
    cudaMalloc(&d_workspace, workspace_size);

    // --- 6. Execute ---
    // Note: alpha and beta MUST remain float even when working with HALF tensors.
    float alpha = 1.0f, beta = 0.0f;

    auto start = std::chrono::steady_clock::now();
    checkCudnn(cudnnConvolutionForward(cudnn, &alpha, input_desc, d_input, filter_desc, d_filter,
                                       conv_desc, algo, d_workspace, workspace_size, &beta,
                                       output_desc, d_output));

    THROW_IF_ERROR(cudaDeviceSynchronize());
    auto end = std::chrono::steady_clock::now();
    std::cout << "Execution time: " << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms" << std::endl;

    // Clean up
    cudaFree(d_workspace);
    cudnnDestroyTensorDescriptor(input_desc);
    cudnnDestroyTensorDescriptor(output_desc);
    cudnnDestroyFilterDescriptor(filter_desc);
    cudnnDestroyConvolutionDescriptor(conv_desc);
    cudnnDestroy(cudnn);
}

__global__ void shmem_tensor_core_convolution_kernel(
    const __half * __restrict__ X, const shape xdims,
    const __half * __restrict__ W, const shape wdims,
    __half * __restrict__ Y, const shape ydims
) {
    constexpr int wmma_m = 16;
    constexpr int wmma_n = 16;
    constexpr int wmma_k = 16;
    constexpr int warp_size = 32;
    namespace wmma = nvcuda::wmma;

    int batch = blockIdx.z;
    int warp_idx = threadIdx.x / warp_size;
    int lane_idx = threadIdx.x % warp_size;
    int num_warps = blockDim.x / warp_size; // must be divisible.
    int block_output_col_num = num_warps * wmma_n;
    int block_output_col_begin = blockIdx.x * block_output_col_num;

    extern __shared__ __half shmem[];

    __half *w = shmem; // shape: wdims.num x round_up_to_multiple(wdims.depth * wdims.height * wdims.width, wmma_k).
    int w_width = ceil_div<int>(wdims.depth * wdims.height * wdims.width, wmma_k) * wmma_k;

    // Unrolled X is loaded into shared memory before loaded into wmma::fragment.
    __half *x_tile = shmem + wdims.num * w_width + warp_idx * wmma_k * wmma_n; // shape: wmma_k x wmma_n. Each warp has its own x_tile.

    // Load W into shared memory.
    for (int i = threadIdx.x; i < wdims.num * w_width; i += blockDim.x) {
        w[i] = 0.0;
    }
    // We load with __half2, assuming wdims.flattened_length() % 2 == 0.
    for (int i = 2 * threadIdx.x; i < wdims.num * wdims.depth * wdims.height * wdims.width; i += 2 * blockDim.x) {
        __half2 elem = *reinterpret_cast<const __half2 *>(W + i);

        int row1 = i / (wdims.depth * wdims.height * wdims.width);
        int col1 = i % (wdims.depth * wdims.height * wdims.width);
        w[row1 * w_width + col1] = elem.x;

        int row2 = (i + 1) / (wdims.depth * wdims.height * wdims.width);
        int col2 = (i + 1) % (wdims.depth * wdims.height * wdims.width);
        w[row2 * w_width + col2] = elem.y;
    }
    __syncthreads();

    wmma::fragment<wmma::accumulator, wmma_m, wmma_n, wmma_k, __half> y_frag;
    wmma::fill_fragment(y_frag, 0.0);
    for (int i = 0; i < wdims.depth * wdims.height * wdims.width; i += wmma_k) {
        wmma::fragment<wmma::matrix_a, wmma_m, wmma_n, wmma_k, __half, wmma::row_major> w_frag;
        wmma::fragment<wmma::matrix_b, wmma_m, wmma_n, wmma_k, __half, wmma::row_major> x_frag;

        // w_frag can be directly loaded from w (i.e. shared memory).
        wmma::load_matrix_sync(w_frag, w + i, w_width);

        // Load a tile of X into shared memory. Each warp loads its own input tile.
        for (int j = lane_idx; j < wmma_k * wmma_n; j += warp_size) {
            // index of unrolled X.
            int input_row = i + j / wmma_n;
            int input_col = block_output_col_begin + warp_idx * wmma_n + j % wmma_n;

            __half elem = 0.0;
            if (input_row < wdims.depth * wdims.height * wdims.width && input_col < ydims.height * ydims.width) {
                // Access x_unrolled[batch][input_row][input_col]
                // -> X[batch][input_row / (wdims.width * wdims.height)][(input_col / ydims.width) + (input_row % (wdims.width * wdims.height) / wdims.width)][(input_col % ydims.width) + (input_row % (wdims.width * wdims.height) % wdims.width)]
                int x_channel = input_row / (wdims.width * wdims.height);
                int x_row = (input_col / ydims.width) + (input_row % (wdims.width * wdims.height) / wdims.width);
                int x_col = (input_col % ydims.width) + (input_row % wdims.width);
                elem = X[((batch * xdims.depth + x_channel) * xdims.height + x_row) * xdims.width + x_col];
            }

            // Store to x_tile.
            x_tile[(j / wmma_n) * wmma_n + (j % wmma_n)] = elem;
        }
        wmma::load_matrix_sync(x_frag, x_tile, wmma_n);

        // matmul
        wmma::mma_sync(y_frag, w_frag, x_frag, y_frag);
    }

    // Write to output. We can reuse the x_tile shared memory of this warp as the padded output
    // tile before writing to global memory.
    __half *y_tile = x_tile;
    wmma::store_matrix_sync(y_tile, y_frag, wmma_n, wmma::mem_row_major);

    // Write to global memory.
    for (int i = lane_idx; i < wmma_m * wmma_n; i += warp_size) {
        int output_row = i / wmma_n;
        int output_col = block_output_col_begin + warp_idx * wmma_n + i % wmma_n;
        if (output_row < ydims.num && output_col < ydims.width * ydims.height) {
            Y[(batch * ydims.depth + output_row) * ydims.height * ydims.width + output_col] = y_tile[i];
        }
    }
}

void convlayer_gpu_opt(
    const __half *X, const shape &xdims,
    const __half *W, const shape &wdims,
    __half *Y, const shape &ydims,
    ConvAlgorithm algorithm
) {
    switch (algorithm) {
        case ConvAlgorithm::CuDNN:
            run_cudnn_convolution(
                X, xdims.num, xdims.depth, xdims.height, xdims.width,
                W, wdims.num, wdims.depth, wdims.height, wdims.width,
                Y, /*pad=*/0, 0, /*stride=*/1, 1
            );
            break;
        case ConvAlgorithm::ShmemTensorCore: {
            int block_size = 128;
            dim3 block_dim(ceil_div<int>(ydims.height * ydims.width, block_size / 32 * 16), 1, xdims.num);
            int shmem_size = sizeof(__half) * (wdims.num * ceil_div<int>(wdims.depth * wdims.height * wdims.width, 16) * 16 + (block_size / 32) * 16 * 16);
            shmem_tensor_core_convolution_kernel<<<block_dim, block_size, shmem_size>>>(X, xdims, W, wdims, Y, ydims);
            break;
        }
    }
}
