#include "kernel.hpp"

#include <iostream>
#include <chrono>
#include <cuda_fp16.h>
#include <cudnn.h>
#include <mma.h>
#include <cuda_runtime.h>

#include "shape.hpp"
#include "common/fmt.hpp"
#include "common/utils.hpp"

// This function is generated by genmini.
void checkCudnn(cudnnStatus_t status) {
    if (status != CUDNN_STATUS_SUCCESS) {
        std::cerr << "cuDNN Error: " << cudnnGetErrorString(status) << std::endl;
        exit(EXIT_FAILURE);
    }
}

// This function is generated by genmini.
void run_cudnn_convolution(
    const __half* d_input,  int in_n, int in_c, int in_h, int in_w,
    const __half* d_filter, int filt_k, int filt_c, int filt_h, int filt_w,
    __half* d_output, int pad_h, int pad_w, int str_h, int str_w)
{
    cudnnHandle_t cudnn;
    checkCudnn(cudnnCreate(&cudnn));

    // --- 1. Describe Input Tensor (NCHW layout with CUDNN_DATA_HALF) ---
    cudnnTensorDescriptor_t input_desc;
    checkCudnn(cudnnCreateTensorDescriptor(&input_desc));
    checkCudnn(cudnnSetTensor4dDescriptor(input_desc, CUDNN_TENSOR_NCHW, CUDNN_DATA_HALF,
                                          in_n, in_c, in_h, in_w));

    // --- 2. Describe Filter (KCHW layout with CUDNN_DATA_HALF) ---
    cudnnFilterDescriptor_t filter_desc;
    checkCudnn(cudnnCreateFilterDescriptor(&filter_desc));
    checkCudnn(cudnnSetFilter4dDescriptor(filter_desc, CUDNN_DATA_HALF, CUDNN_TENSOR_NCHW,
                                          filt_k, filt_c, filt_h, filt_w));

    // --- 3. Describe Convolution Math ---
    // Note: We use CUDNN_DATA_FLOAT for math precision (Pseudo-FP16 mode).
    // This accumulates math in FP32 to prevent underflow/overflow, which is highly
    // recommended by NVIDIA for performance and stability on Tensor Cores.
    cudnnConvolutionDescriptor_t conv_desc;
    checkCudnn(cudnnCreateConvolutionDescriptor(&conv_desc));
    checkCudnn(cudnnSetConvolution2dDescriptor(conv_desc, pad_h, pad_w, str_h, str_w,
                                               1, 1, CUDNN_CROSS_CORRELATION, CUDNN_DATA_FLOAT));

    // Explicitly enable Tensor Core acceleration math mode if needed (cuDNN 8 usually handles this automatically)
    checkCudnn(cudnnSetConvolutionMathType(conv_desc, CUDNN_DEFAULT_MATH));

    // --- 4. Determine Output Shape ---
    int out_n, out_c, out_h, out_w;
    checkCudnn(cudnnGetConvolution2dForwardOutputDim(conv_desc, input_desc, filter_desc,
                                                     &out_n, &out_c, &out_h, &out_w));

    cudnnTensorDescriptor_t output_desc;
    checkCudnn(cudnnCreateTensorDescriptor(&output_desc));
    checkCudnn(cudnnSetTensor4dDescriptor(output_desc, CUDNN_TENSOR_NCHW, CUDNN_DATA_HALF,
                                          out_n, out_c, out_h, out_w));

#if 0
    // --- 5. Find Best Algorithm (Modern cuDNN 8+ Approach) ---
    int requested_algo_count = 1;
    int returned_algo_count = 0;
    cudnnConvolutionFwdAlgoPerf_t perf_results;

    checkCudnn(cudnnFindConvolutionForwardAlgorithm(
        cudnn,
        input_desc,
        filter_desc,
        conv_desc,
        output_desc,
        requested_algo_count,
        &returned_algo_count,
        &perf_results));

    cudnnConvolutionFwdAlgo_t algo = perf_results.algo;
    size_t workspace_size = perf_results.memory;

    if (perf_results.status != CUDNN_STATUS_SUCCESS) {
      std::cerr << "No suitable algorithm found!" << std::endl;
      exit(EXIT_FAILURE);
    }
#else
    cudnnConvolutionFwdAlgo_t algo = CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM;
    std::size_t workspace_size;
    checkCudnn(cudnnGetConvolutionForwardWorkspaceSize(
      cudnn,
      input_desc,
      filter_desc,
      conv_desc,
      output_desc,
      algo,
      &workspace_size
    ));
#endif
    std::cout << "CuDNN using algorithm: " << static_cast<int>(algo) << std::endl;
    std::cout << "Workspace size: " << workspace_size << std::endl;

    void* d_workspace{nullptr};
    cudaMalloc(&d_workspace, workspace_size);

    // --- 6. Execute ---
    // Note: alpha and beta MUST remain float even when working with HALF tensors.
    float alpha = 1.0f, beta = 0.0f;

    auto start = std::chrono::steady_clock::now();
    checkCudnn(cudnnConvolutionForward(cudnn, &alpha, input_desc, d_input, filter_desc, d_filter,
                                       conv_desc, algo, d_workspace, workspace_size, &beta,
                                       output_desc, d_output));

    THROW_IF_ERROR(cudaDeviceSynchronize());
    auto end = std::chrono::steady_clock::now();
    std::cout << "Execution time: " << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms" << std::endl;

    // Clean up
    cudaFree(d_workspace);
    cudnnDestroyTensorDescriptor(input_desc);
    cudnnDestroyTensorDescriptor(output_desc);
    cudnnDestroyFilterDescriptor(filter_desc);
    cudnnDestroyConvolutionDescriptor(conv_desc);
    cudnnDestroy(cudnn);
}

void convlayer_gpu_opt(
    const __half *X, const shape &xdims,
    const __half *W, const shape &wdims,
    __half *Y, const shape &ydims,
    ConvAlgorithm algorithm
) {
    switch (algorithm) {
        case ConvAlgorithm::CuDNN:
            run_cudnn_convolution(
                X, xdims.num, xdims.depth, xdims.height, xdims.width,
                W, wdims.num, wdims.depth, wdims.height, wdims.width,
                Y, /*pad=*/0, 0, /*stride=*/1, 1
            );
            break;
    }
}
