#include "kernel.hpp"

#include <chrono>
#include <cstddef>
#include <cudnn.h>
#include <cuda_runtime.h>
#include <iostream>
#include <nvtx3/nvToolsExt.h>

#include "common/fmt.hpp"
#include "common/utils.hpp"

// Computes ceil(x / y)
std::size_t ceil_div(std::size_t x, std::size_t y) {
  std::size_t offset = x % y == 0 ? 0 : 1;
  return x / y + offset;
}

// A better baseline than the one defined in main.cu.
// 1 thread outputs 1 feature image.
__global__ void baseline_conv_kernel(const float *X, const shape xdims, const float *W, const shape wdims, float *Y, const shape ydims) {
  const std::size_t global_idx = blockIdx.x * blockDim.x + threadIdx.x;
  if (global_idx < ydims.num * ydims.depth) {
    std::size_t batch_idx  = global_idx / ydims.depth; // this thread process this input image
    std::size_t filter_idx = global_idx % ydims.depth; // and this filter

    for (std::size_t i = 0; i < ydims.height; i++) {
      for (std::size_t j = 0; j < ydims.width; j++) {
        // Compute Y[batch_idx][filter_idx][i][j]
        float output = 0.0f;
        for (std::size_t c = 0; c < wdims.depth; c++) {
          for (std::size_t p = 0; p < wdims.height; p++) {
            for (std::size_t q = 0; q < wdims.width; q++) {
              // Y[batch_idx][filter_idx][i][j] += X[batch_idx][c][i+p][j+q] * W[filter_idx][c][p][q]
              float x = X[((batch_idx * xdims.depth + c) * xdims.height + (i + p)) * xdims.width + (j + q)];
              float w = W[((filter_idx * wdims.depth + c) * wdims.height + p) * wdims.width + q];
              output += x * w;
            }
          }
        }
        Y[((batch_idx * ydims.depth + filter_idx) * ydims.height + i) * ydims.width + j] = output;
      }
    }
  }
}

void checkCudnn(cudnnStatus_t status) {
    if (status != CUDNN_STATUS_SUCCESS) {
        std::cerr << "cuDNN Error: " << cudnnGetErrorString(status) << std::endl;
        exit(EXIT_FAILURE);
    }
}

// The cudnn code (and checkCudnn) are generated by genmini.
void run_cudnn_convolution(
    const float* d_input,  int in_n, int in_c, int in_h, int in_w,
    const float* d_filter, int filt_k, int filt_c, int filt_h, int filt_w,
    float* d_output, int pad_h, int pad_w, int str_h, int str_w)
{
    cudnnHandle_t cudnn;
    checkCudnn(cudnnCreate(&cudnn));

    // --- 1. Describe Input Tensor (NCHW layout) ---
    cudnnTensorDescriptor_t input_desc;
    checkCudnn(cudnnCreateTensorDescriptor(&input_desc));
    checkCudnn(cudnnSetTensor4dDescriptor(input_desc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT,
                                          in_n, in_c, in_h, in_w));

    // --- 2. Describe Filter (KCHW layout) ---
    cudnnFilterDescriptor_t filter_desc;
    checkCudnn(cudnnCreateFilterDescriptor(&filter_desc));
    checkCudnn(cudnnSetFilter4dDescriptor(filter_desc, CUDNN_DATA_FLOAT, CUDNN_TENSOR_NCHW,
                                          filt_k, filt_c, filt_h, filt_w));

    // --- 3. Describe Convolution Math ---
    cudnnConvolutionDescriptor_t conv_desc;
    checkCudnn(cudnnCreateConvolutionDescriptor(&conv_desc));
    checkCudnn(cudnnSetConvolution2dDescriptor(conv_desc, pad_h, pad_w, str_h, str_w,
                                               1, 1, CUDNN_CROSS_CORRELATION, CUDNN_DATA_FLOAT));

    // --- 4. Determine Output Shape ---
    int out_n, out_c, out_h, out_w;
    checkCudnn(cudnnGetConvolution2dForwardOutputDim(conv_desc, input_desc, filter_desc,
                                                     &out_n, &out_c, &out_h, &out_w));

    cudnnTensorDescriptor_t output_desc;
    checkCudnn(cudnnCreateTensorDescriptor(&output_desc));
    checkCudnn(cudnnSetTensor4dDescriptor(output_desc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT,
                                          out_n, out_c, out_h, out_w));

#if 0
    // --- 5. Find Best Algorithm (Modern cuDNN 8+ Approach) ---
    int requested_algo_count = 1;
    int returned_algo_count = 0;
    cudnnConvolutionFwdAlgoPerf_t perf_results;

    // This function actually benchmarks the algorithms on your GPU
    checkCudnn(cudnnFindConvolutionForwardAlgorithm(
        cudnn,
        input_desc,
        filter_desc,
        conv_desc,
        output_desc,
        requested_algo_count,
        &returned_algo_count,
        &perf_results));

    // Grab the algorithm and workspace size from the results
    cudnnConvolutionFwdAlgo_t algo = perf_results.algo;
    size_t workspace_size = perf_results.memory;

    // Check if the algo actually works (status should be CUDNN_STATUS_SUCCESS)
    if (perf_results.status != CUDNN_STATUS_SUCCESS) {
      std::cerr << "No suitable algorithm found!" << std::endl;
      exit(EXIT_FAILURE);
    }
#else
    cudnnConvolutionFwdAlgo_t algo = CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM;
    std::size_t workspace_size;
    checkCudnn(cudnnGetConvolutionForwardWorkspaceSize(
      cudnn,
      input_desc,
      filter_desc,
      conv_desc,
      output_desc,
      algo,
      &workspace_size
    ));
#endif
    std::cout << "CuDNN using algorithm: " << static_cast<int>(algo) << std::endl;
    std::cout << "Workspace size: " << workspace_size << std::endl;

    void* d_workspace{nullptr};
    cudaMalloc(&d_workspace, workspace_size);

    // --- 6. Execute ---
    float alpha = 1.0f, beta = 0.0f;
    nvtxRangePushA("Inference_Kernel");
    auto start = std::chrono::steady_clock::now();
    checkCudnn(cudnnConvolutionForward(cudnn, &alpha, input_desc, d_input, filter_desc, d_filter,
                                       conv_desc, algo, d_workspace, workspace_size, &beta,
                                       output_desc, d_output));
    nvtxRangePop();

    THROW_IF_ERROR(cudaDeviceSynchronize());
    auto end = std::chrono::steady_clock::now();
    std::cout << "Execution time: " << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms" << std::endl;

    // Clean up
    cudaFree(d_workspace);
    cudnnDestroyTensorDescriptor(input_desc);
    cudnnDestroyTensorDescriptor(output_desc);
    cudnnDestroyFilterDescriptor(filter_desc);
    cudnnDestroyConvolutionDescriptor(conv_desc);
    cudnnDestroy(cudnn);
}

__constant__ float conv_filter[16384]; // 64KB

template <std::size_t NUM_OUTPUTS, std::size_t R, std::size_t S>
__global__ void conv_forward_register_tiled_matmul_kernel(
  const float *X, const shape xdims,
  float *Y, const shape ydims
) {
  // #define Y3d(b, n, i) Y[(((b) * ydims.depth) + (n)) * ydims.height * ydims.width + (i)]
  // Each thread computes Y3d[batch, :, outputColumn], which is a column of NUM_OUTPUTS elements.
  std::size_t batch = blockIdx.z;
  std::size_t outputColumn = blockIdx.x * blockDim.x + threadIdx.x;
  std::size_t C = xdims.depth;

  if (outputColumn >= ydims.height * ydims.width) {
    return;
  }

  // The outputs, which is a sub-column of Y.
  float outputs[NUM_OUTPUTS];

  #pragma unroll
  for (std::size_t i = 0; i < NUM_OUTPUTS; i++) {
    outputs[i] = 0.0f;
  }

  constexpr std::size_t STEP_SIZE = R * S;
  for (std::size_t i = 0; i < C * R * S; i += STEP_SIZE) {
    // Load a tile from X into registers.
    float X_tile[STEP_SIZE];

    #pragma unroll
    for (std::size_t j = 0; j < STEP_SIZE; j++) {
      if (i + j >= C * R * S) {
        X_tile[j] = 0.0f;
      }
      else {
        X_tile[j] = X[((batch * C + ((i+j)/(R*S))) * xdims.height + (outputColumn / ydims.width + (i+j)%(R*S) / S)) * xdims.width + (outputColumn % ydims.width + (i+j) % S)];
      }
    }

    // Tiled matrix multiplication.
    #pragma unroll
    for (std::size_t j = 0; j < NUM_OUTPUTS; j++) {
      if (j >= ydims.depth) {
        break;
      }

      #pragma unroll
      for (std::size_t k = 0; k < STEP_SIZE; k++) {
        outputs[j] += conv_filter[j * (C * R * S) + (i + k)] * X_tile[k];
      }
    }
  }

  #pragma unroll
  for (std::size_t i = 0; i < NUM_OUTPUTS; i++) {
    if (i >= ydims.depth) {
      break;
    }

    Y[(batch * ydims.depth + i) * ydims.height * ydims.width + outputColumn] = outputs[i];
  }
}

template <std::size_t NUM_OUTPUTS, std::size_t R, std::size_t S>
__global__ void conv_forward_shmem_register_tiled_matmul_kernel(
  const float *X, const shape xdims,
  float *Y, const shape ydims
) {
  // #define Y3d(b, n, i) Y[(((b) * ydims.depth) + (n)) * ydims.height * ydims.width + (i)]
  // Each thread computes Y3d[batch, :, outputColumn], which is a column of NUM_OUTPUTS elements.
  std::size_t batch = blockIdx.z;
  std::size_t outputColumn = blockIdx.x * blockDim.x + threadIdx.x;

  // Load a tile of X to shared memory first for memory reuse.
  // size: elements of X used, including halo cells.
  extern __shared__ float XTileShared[];

  // The outputs, which is a sub-column of Y.
  float outputs[NUM_OUTPUTS];

  #pragma unroll
  for (std::size_t i = 0; i < NUM_OUTPUTS; i++) {
    outputs[i] = 0.0f;
  }

  int block_input_row_offset = blockIdx.x * (blockDim.x / ydims.width);
  int block_input_row_num = blockDim.x / ydims.width + R - 1;

  // For each channel, load a tile into shared memory, and then to registers.
  for (std::size_t channel = 0; channel < xdims.depth; channel++) {
    // 1. Load rows of X into shared memory.
    const float *X_rows_begin = X + ((batch * xdims.depth + channel) * xdims.height + block_input_row_offset) * xdims.width;
    if (reinterpret_cast<std::uintptr_t>(X_rows_begin) % sizeof(float2) == 0) { // The first element is aligned to multiple of 8.
      for (std::size_t i = threadIdx.x; 2 * i < block_input_row_num * xdims.width; i += blockDim.x) {
        if (2 * i + 1 == block_input_row_num * xdims.width) {
          // Last element of an odd number of inputs. Load a single float.
          float elem = *(X_rows_begin + 2 * i);
          XTileShared[2*i] = elem;
        }
        else {
          float2 elem = reinterpret_cast<const float2 *>(X_rows_begin)[i];
          XTileShared[2*i] = elem.x;
          XTileShared[2*i+1] = elem.y;
        }
      }
    }
    else { // The first element is not aligned to multiple of 8.
      for (std::size_t i = threadIdx.x; 2 * i <= block_input_row_num * xdims.width; i += blockDim.x) {
        if (i == 0) {
          // Misaligned first element. Load a single float.
          float elem = *(X_rows_begin + 2 * i);
          XTileShared[2*i] = elem;
        }
        else if (2 * i == block_input_row_num * xdims.width) {
          // Misaligned last element.
          float elem = *(X_rows_begin + 2 * i - 1);
          XTileShared[2*i-1] = elem;
        }
        else {
          float2 elem = reinterpret_cast<const float2 *>(X_rows_begin - 1)[i];
          XTileShared[2*i-1] = elem.x;
          XTileShared[2*i] = elem.y;
        }
      }
    }
    __syncthreads();

    float *X_data = &XTileShared[(threadIdx.x / ydims.width) * xdims.width + (threadIdx.x % ydims.width)];
    float XTile[S];

    for (std::size_t i = 0; i < R * S; i += S) {
      // 2. Load a tile of X from shared memory -> registers.
      #pragma unroll
      for (std::size_t j = 0; j < S; j++) {
        XTile[j] = *X_data;
        X_data++;
      }

      // 3. Accumulate to the outpus.
      #pragma unroll
      for (std::size_t j = 0; j < NUM_OUTPUTS; j++) {
        if (j >= ydims.depth) {
          break;
        }

        #pragma unroll
        for (int k = 0; k < S; k++) {
          outputs[j] += conv_filter[j * R * S + (i + k)] * XTile[k];
        }
      }

      X_data += ydims.width - 1;
    }
    __syncthreads();
  }

  #pragma unroll
  for (std::size_t i = 0; i < NUM_OUTPUTS; i++) {
    if (i >= ydims.depth) {
      break;
    }

    Y[(batch * ydims.depth + i) * ydims.height * ydims.width + outputColumn] = outputs[i];
  }
}

void convlayer_gpu_opt(const float *X, const shape &xdims, const float *W, const shape &wdims, float *Y, const shape &ydims,
                       ConvAlgorithm algorithm) {
  switch (algorithm) {
    case ConvAlgorithm::CuDNN: {
      run_cudnn_convolution(
        X, xdims.num, xdims.depth, xdims.height, xdims.width,
        W, wdims.num, wdims.depth, wdims.height, wdims.width,
        Y, /*pad=*/0, 0, /*stride=*/1, 1
      );
      break;
    }
    case ConvAlgorithm::Baseline: {
      dim3 dim_grid(ceil_div(ydims.num * ydims.depth, 256));
      dim3 dim_block(256); // This size is chosen arbitrarily.
      baseline_conv_kernel<<<dim_grid, dim_block>>>(X, xdims, W, wdims, Y, ydims);
      THROW_IF_ERROR(cudaGetLastError());
      THROW_IF_ERROR(cudaDeviceSynchronize());
      break;
    }
    case ConvAlgorithm::MatmulConceptualUnrollingRegisterTiled: {
      if (wdims.width == 5 && wdims.height == 5) {
        THROW_IF_ERROR(cudaMemcpyToSymbol(conv_filter, W, sizeof(float) * wdims.flattened_length(), /*offset=*/0, cudaMemcpyDefault));

        const int blockSize = 64;
        constexpr std::size_t R = 5, S = 5;

        dim3 dimGrid(ceil_div(ydims.height * ydims.width, blockSize), 1, ydims.num);

        if (wdims.num <= 4) {
          conv_forward_register_tiled_matmul_kernel<4, R, S><<<dimGrid, blockSize>>>(X, xdims, Y, ydims);
        }
        else if (wdims.num <= 8) {
          conv_forward_register_tiled_matmul_kernel<8, R, S><<<dimGrid, blockSize>>>(X, xdims, Y, ydims);
        }
        else if (wdims.num <= 16) {
          conv_forward_register_tiled_matmul_kernel<16, R, S><<<dimGrid, blockSize>>>(X, xdims, Y, ydims);
        }
        else if (wdims.num <= 32) {
          conv_forward_register_tiled_matmul_kernel<32, R, S><<<dimGrid, blockSize>>>(X, xdims, Y, ydims);
        }
        THROW_IF_ERROR(cudaGetLastError());
        THROW_IF_ERROR(cudaDeviceSynchronize());
      }
      else {
        std::cerr << "Unsupported size for MatmulConceptualUnrollingRegisterTiled" << std::endl;
      }
      break;
    }
    case ConvAlgorithm::MatmulConceptualUnrollingShmemRegisterTiled: {
      // Constant memory is used to store the convolution filter.
      THROW_IF_ERROR(cudaMemcpyToSymbol(conv_filter, W, sizeof(float) * wdims.flattened_length(), /*offset=*/0, cudaMemcpyDefault));

      // This block size is a factor of ydims.height * ydims.width, and a multiple of ydims.width.
      // We use a simple algorithm to find the suitable block size: always pick the largest
      // value that is <= 512. This will give a minimum occupacy of 66.8% (when ydims.width =
      // 171) on a Nvidia T4 which has 1024 threads / SM.
      int rows = 512 / ydims.width;
      while (rows > 0) {
        if (ydims.height % rows == 0) {
          break;
        }
        rows--;
      }
      if (rows == 0) {
        std::cerr << "Unsupported size for MatmulConceptualUnrollingRegisterTiled" << std::endl;
        break;
      }
      int blockSize = rows * ydims.width;

      dim3 dimGrid(ydims.height * ydims.width / blockSize, 1, ydims.num);
      std::size_t shared_memory_size = sizeof(float) * (rows + wdims.height - 1) * xdims.width;
      std::cout << "dimGrid = (" << dimGrid.x << ", " << dimGrid.y << ", " << dimGrid.z << ")" << std::endl;
      std::cout << "blockSize = " << blockSize << std::endl;
      std::cout << "sharedMem = " << shared_memory_size << "B" << std::endl;

      if (wdims.width == 5 && wdims.height == 5) {
        constexpr std::size_t R = 5, S = 5;

        if (wdims.num <= 4) {
          conv_forward_shmem_register_tiled_matmul_kernel<4, R, S><<<dimGrid, blockSize, shared_memory_size>>>(X, xdims, Y, ydims);
        }
        else if (wdims.num <= 8) {
          conv_forward_shmem_register_tiled_matmul_kernel<8, R, S><<<dimGrid, blockSize, shared_memory_size>>>(X, xdims, Y, ydims);
        }
        else if (wdims.num <= 16) {
          conv_forward_shmem_register_tiled_matmul_kernel<16, R, S><<<dimGrid, blockSize, shared_memory_size>>>(X, xdims, Y, ydims);
        }
        else if (wdims.num <= 32) {
          conv_forward_shmem_register_tiled_matmul_kernel<32, R, S><<<dimGrid, blockSize, shared_memory_size>>>(X, xdims, Y, ydims);
        }
        THROW_IF_ERROR(cudaGetLastError());
        THROW_IF_ERROR(cudaDeviceSynchronize());
      }
      else if (wdims.width == 3 && wdims.height == 3) {
        constexpr std::size_t R = 3, S = 3;

        if (wdims.num <= 4) {
          conv_forward_shmem_register_tiled_matmul_kernel<4, R, S><<<dimGrid, blockSize, shared_memory_size>>>(X, xdims, Y, ydims);
        }
        else if (wdims.num <= 8) {
          conv_forward_shmem_register_tiled_matmul_kernel<8, R, S><<<dimGrid, blockSize, shared_memory_size>>>(X, xdims, Y, ydims);
        }
        else if (wdims.num <= 16) {
          conv_forward_shmem_register_tiled_matmul_kernel<16, R, S><<<dimGrid, blockSize, shared_memory_size>>>(X, xdims, Y, ydims);
        }
        else if (wdims.num <= 32) {
          conv_forward_shmem_register_tiled_matmul_kernel<32, R, S><<<dimGrid, blockSize, shared_memory_size>>>(X, xdims, Y, ydims);
        }
        THROW_IF_ERROR(cudaGetLastError());
        THROW_IF_ERROR(cudaDeviceSynchronize());
      }
      else {
        std::cerr << "Unsupported size for MatmulConceptualUnrollingRegisterTiled" << std::endl;
      }
      break;
    }
    default:
      std::cerr << "Invalid convolution algorithm {}" << static_cast<int>(algorithm) << std::endl;
  }
}
